{% set version = "2.7.0" %}

package:
  name: snpy
  version: {{ version }}

source:
   #git_tag: {{ version }}
   #git_url: https://github.com/obscode/snpy.git
   path: /Users/cburns/src/snpy

requirements:
   build:
      - python
      - setuptools
      - {{ compiler('c') }}
      - scikit-learn==0.24.2

   run:
      - python
      - numpy
      - scipy
      - pymysql
      - matplotlib
      - ipython
      - scikit-learn==0.24.2
      - astropy

test:
   requires:
      - pytest
   source_files:
      - tests
   commands:
      - cd tests
      - echo $(pwd)
      - echo $(which pytest)
      - pytest

about:
   home: http://csp.obs.carnegiescience.edu/data/snpy
   license: MIT
   license_file: LICENSE
   summary: A python package for analysis of supernova light-curves.
